- name: Ceph health 
  shell: ceph -s 

- block:
   - name: Install ceph-ansible
     yum: name=ceph-ansible state=present
  rescue:
    - name: if the previous command did not succeed try installing from rpm
      yum: name=wget state=present

    - name: if the previous command did not succeed try installing from rpm
      shell: "{{item}}"
      with_items:
        - "wget http://cbs.centos.org/kojifiles/packages/ceph-ansible/2.1.9/3.gfd93045.el7/noarch/ceph-ansible-2.1.9-3.gfd93045.el7.noarch.rpm"
        - "rpm -i ceph-ansible-2.1.9-3.gfd93045.el7.noarch.rpm"



