- include: rhel.yml
  when:
     - ansible_distribution == 'RedHat'
     - install.containers.enabled == False

- include: rhel-cont.yml
  when:
     - ansible_distribution == 'RedHat'
     - install.containers.enabled == True

- include: centos.yml
  when: ansible_distribution == 'CentOS'
